name: CI - app

on: [workflow_dispatch]

env:
  PYTHON_VERSION: 3.13

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Compile to single binary
        run: pyinstaller updater.py -F -n updater-linux-amd64
      
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: updater-linux
          path: dist/updater-linux-amd64

  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Compile to single binary
        run: pyinstaller updater.py -F -n updater-windows-amd64.exe

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: updater-windows
          path: dist\updater-windows-amd64.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Compile to single binary
        run: pyinstaller updater.py -F -n updater-macos-arm64
      
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: updater-macos
          path: dist/updater-macos-arm64

  create_release:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download linux artifact
        uses: actions/download-artifact@v4
        with:
          name: updater-linux
          path: release_artifacts

      - name: Download windows artifact
        uses: actions/download-artifact@v4
        with:
          name: updater-windows
          path: release_artifacts

      - name: Download mac artifact
        uses: actions/download-artifact@v4
        with:
          name: updater-macos
          path: release_artifacts

      - name: List release_artifacts
        run: ls -lah release_artifacts

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: release_artifacts/*
          body: 'Source code (zip) and Source code (tar.gz) were auto-generated by GitHub and contain the uncompiled scripts'
          commit: main
          name: 'MF-updater v${{ github.run_number }}'
          tag: v${{ github.run_number }}
