name: CI - app

on:
  push:
    branches: [main]
    paths: ['updater.py']
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Compile to single binary
        run: pyinstaller updater.py --onefile && ls -lah dist

  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Compile to single binary
        run: pyinstaller updater.py --onefile && dir dist
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Compile to single binary
        run: pyinstaller updater.py --onefile && ls -lah dist
